import 'package:world_time/services/worldtime.dart';

class Region {
  static List<WorldTime> locations = [
    WorldTime(location: 'africa', gmt: '+02:00'),
    WorldTime(location: 'albania', gmt: '+01:00'),
    WorldTime(location: 'argentina', gmt: '-03:00'),
    WorldTime(location: 'australia', gmt: '+11:00'),
    WorldTime(location: 'bangladesh', gmt: '+06:00'),
    WorldTime(location: 'belgium', gmt: '+01:00'),
    WorldTime(location: 'bosnia', gmt: '+01:00'),
    WorldTime(location: 'brazil', gmt: '-03:00'),
    WorldTime(location: 'cameroon', gmt: '+01:00'),
    WorldTime(location: 'canada', gmt: '-05:00'),
    WorldTime(location: 'chad', gmt: '+01:00'),
    WorldTime(location: 'china', gmt: '+08:00'),
    WorldTime(location: 'croatia', gmt: '+01:00'),
    WorldTime(location: 'czech', gmt: '+01:00'),
    WorldTime(location: 'denmark', gmt: '+01:00'),
    WorldTime(location: 'estonia', gmt: '+02:00'),
    WorldTime(location: 'finland', gmt: '+02:00'),
    WorldTime(location: 'france', gmt: '+01:00'),
    WorldTime(location: 'germany', gmt: '+01:00'),
    WorldTime(location: 'greece', gmt: '+02:00'),
    WorldTime(location: 'hungary', gmt: '+01:00'),
    WorldTime(location: 'india', gmt: '+05:30'),
    WorldTime(location: 'ireland', gmt: '+00:00'),
    WorldTime(location: 'israel', gmt: '+02:00'),
    WorldTime(location: 'italy', gmt: '+01:00'),
    WorldTime(location: 'jamaica', gmt: '-05:00'),
    WorldTime(location: 'korea', gmt: '+09:00'),
    WorldTime(location: 'latvia', gmt: '+02:00'),
    WorldTime(location: 'lithuania', gmt: '+02:00'),
    WorldTime(location: 'luxembourg', gmt: '+01:00'),
    WorldTime(location: 'macedonia', gmt: '+01:00'),
    WorldTime(location: 'netherlands', gmt: '+01:00'),
    WorldTime(location: 'norway', gmt: '+01:00'),
    WorldTime(location: 'poland', gmt: '+01:00'),
    WorldTime(location: 'portugal', gmt: '-01:00'),
    WorldTime(location: 'russia', gmt: '+03:00'),
    WorldTime(location: 'slovakia', gmt: '+01:00'),
    WorldTime(location: 'sweden', gmt: '+01:00'),
    WorldTime(location: 'switzerland', gmt: '+01:00'),
    WorldTime(location: 'turkey', gmt: '+03:00'),
    WorldTime(location: 'uk', gmt: '+00:00'),
    WorldTime(location: 'ukraine', gmt: '+02:00'),
    WorldTime(location: 'usa', gmt: '-05:00'),
  ];
}
